language: cpp

compiler:
  - clang

script:
  - make tests


notifications:
  slack:
    rooms: 
      - nyuoop:0ll9o0yls3X6yg6AgMHHYbmX #your_TA_slack_channel
    on_success: always
    on_failure: never
  email:
    recipients:
      - your_email@nyu.edu
    on_success: always
    on_failure: always  
